export interface Chapter {
  id: string;
  slug: string;
  title: string;
  estimatedMinutes: number;
  tags: string[];
  hasAiSection: boolean;
  minPlan: "free" | "premium" | "pro";
  quote?: { text: string; author: string };
  summary: string[];
}

export interface Module {
  id: string;
  slug: string;
  title: string;
  icon: string;
  description: string;
  gradient: string;
  minPlan: "free" | "premium" | "pro";
  chapters: Chapter[];
}

export const MODULES: Module[] = [
  {
    id: "m1",
    slug: "presupuesto-ahorro",
    title: "Presupuesto y Ahorro",
    icon: "💰",
    description: "Aprende a controlar tu dinero antes de que él te controle a ti.",
    gradient: "from-emerald-600 to-teal-500",
    minPlan: "free",
    chapters: [
      {
        id: "m1c1",
        slug: "que-es-presupuesto",
        title: "¿Qué es un presupuesto y por qué importa?",
        estimatedMinutes: 4,
        tags: ["presupuesto", "básico", "finanzas"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Un presupuesto te dice a dónde va tu dinero en vez de preguntarte a dónde fue.", author: "Dave Ramsey" },
        summary: [
          "Un presupuesto es simplemente un plan para tu dinero antes de gastarlo.",
          "Sin presupuesto, gastas por impulso; con presupuesto, gastas con intención.",
          "Solo necesitas 15 minutos al mes para crear uno que funcione.",
        ],
      },
      {
        id: "m1c2",
        slug: "regla-50-30-20",
        title: "La regla 50/30/20 explicada con ejemplos",
        estimatedMinutes: 5,
        tags: ["50/30/20", "presupuesto", "ahorro"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "No es cuánto ganas, sino cuánto guardas.", author: "Robert Kiyosaki" },
        summary: [
          "50% de tus ingresos para necesidades (renta, comida, transporte básico).",
          "30% para deseos (ocio, ropa, restaurantes).",
          "20% para ahorro e inversión — esto va primero, no lo que sobra.",
        ],
      },
      {
        id: "m1c3",
        slug: "metodo-sobres",
        title: "El método de los sobres",
        estimatedMinutes: 4,
        tags: ["presupuesto", "método sobres", "control"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "El efectivo en mano hace el dolor de gastar real.", author: "Dave Ramsey" },
        summary: [
          "Asigna dinero físico (o virtual) a sobres por categoría.",
          "Cuando el sobre está vacío, paras de gastar en esa categoría.",
          "Elimina el gasto inconsciente con tarjeta.",
        ],
      },
      {
        id: "m1c4",
        slug: "pagar-primero-a-ti",
        title: "Pagar primero a ti mismo",
        estimatedMinutes: 3,
        tags: ["ahorro", "automatización", "hábito"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Guarda una parte de todo lo que ganas para ti mismo.", author: "El Hombre más Rico de Babilonia" },
        summary: [
          "Transfiere el ahorro automáticamente el día de cobro, antes de cualquier gasto.",
          "Empieza con el 1% si es necesario — lo que importa es el hábito.",
          "El dinero que no ves, no lo gastas.",
        ],
      },
      {
        id: "m1c5",
        slug: "primer-presupuesto-buco",
        title: "Cómo crear tu primer presupuesto en Buco",
        estimatedMinutes: 5,
        tags: ["buco", "tutorial", "presupuesto"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Una meta sin un plan es solo un deseo.", author: "Antoine de Saint-Exupéry" },
        summary: [
          "Usa Cuentas → Límites por Categoría para asignar presupuesto por tipo de gasto.",
          "Buco te avisa cuando llegas al 70% del límite de una categoría.",
          "Revisa tu presupuesto cada domingo en 5 minutos.",
        ],
      },
      {
        id: "m1c6",
        slug: "analisis-tu-presupuesto",
        title: "Análisis de tu presupuesto actual",
        estimatedMinutes: 3,
        tags: ["IA", "personalizado", "presupuesto"],
        hasAiSection: true,
        minPlan: "free",
        quote: { text: "Los datos no mienten. Lo que mide, mejora.", author: "Peter Drucker" },
        summary: [
          "Claude analiza tu distribución real de gastos vs la regla 50/30/20.",
          "Identifica las categorías donde más te excedes.",
          "Propone ajustes concretos con tus números reales.",
        ],
      },
    ],
  },
  {
    id: "m2",
    slug: "tarjetas-intereses",
    title: "Tarjetas de Crédito e Intereses",
    icon: "💳",
    description: "Entiende cómo funcionan las tarjetas y úsalas a tu favor.",
    gradient: "from-blue-600 to-indigo-500",
    minPlan: "free",
    chapters: [
      {
        id: "m2c1",
        slug: "como-funciona-tarjeta",
        title: "¿Cómo funciona realmente una tarjeta de crédito?",
        estimatedMinutes: 5,
        tags: ["crédito", "básico", "intereses"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Una tarjeta de crédito es un préstamo disfrazado de conveniencia.", author: "Suze Orman" },
        summary: [
          "La tarjeta te presta dinero por ~30 días sin interés — si pagas el total.",
          "Si pagas mínimo, el banco aplica interés sobre el saldo restante.",
          "El ciclo de corte y pago es clave para no pagar intereses.",
        ],
      },
      {
        id: "m2c2",
        slug: "cat-apr-tin",
        title: "El CAT, APR y TIN: qué significan en tu bolsillo",
        estimatedMinutes: 4,
        tags: ["CAT", "APR", "intereses", "tasas"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "El precio real del crédito está en la letra pequeña.", author: "Warren Buffett" },
        summary: [
          "CAT (Costo Anual Total) incluye todos los cargos — es el número real a comparar.",
          "APR es la tasa anual; TIN es la tasa nominal sin comisiones.",
          "Una tarjeta con CAT de 60% duplica tu deuda en poco más de un año.",
        ],
      },
      {
        id: "m2c3",
        slug: "peligro-pago-minimo",
        title: "El peligro del pago mínimo",
        estimatedMinutes: 5,
        tags: ["pago mínimo", "deuda", "intereses"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "El pago mínimo está diseñado para hacerte rico al banco, no a ti.", author: "Dave Ramsey" },
        summary: [
          "Pagar solo el mínimo en $5,000 puede costarte el triple en intereses.",
          "El banco diseña el pago mínimo para maximizar lo que le pagas.",
          "Calcula el tiempo real de pago con la calculadora de este capítulo.",
        ],
      },
      {
        id: "m2c4",
        slug: "utilizacion-credito",
        title: "Utilización de crédito y tu score",
        estimatedMinutes: 4,
        tags: ["score", "crédito", "utilización"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Tu score crediticio es tu reputación financiera.", author: "Suze Orman" },
        summary: [
          "Usar más del 30% de tu límite baja tu score crediticio.",
          "Mantener utilización baja mejora tu historial aunque pagues puntual.",
          "Buco muestra tu porcentaje de utilización en tiempo real.",
        ],
      },
      {
        id: "m2c5",
        slug: "usar-credito-a-favor",
        title: "Estrategia para usar el crédito a tu favor",
        estimatedMinutes: 4,
        tags: ["crédito", "estrategia", "cashback"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Las personas ricas usan el crédito para crear riqueza; los pobres, para aparentarla.", author: "Robert Kiyosaki" },
        summary: [
          "Usa tarjeta solo para lo que ya tienes dinero en cuenta.",
          "Elige tarjetas con cashback o puntos que realmente uses.",
          "Paga el total antes del corte — nunca el mínimo.",
        ],
      },
      {
        id: "m2c6",
        slug: "estado-tus-tarjetas",
        title: "Estado de tus tarjetas actuales",
        estimatedMinutes: 3,
        tags: ["IA", "personalizado", "tarjetas"],
        hasAiSection: true,
        minPlan: "free",
        quote: { text: "Conocer tu deuda exacta es el primer paso para eliminarla.", author: "Tony Robbins" },
        summary: [
          "Claude analiza el saldo, límite y utilización de cada tarjeta.",
          "Identifica cuál tarjeta te está costando más en intereses.",
          "Sugiere el orden óptimo de pago según tus datos.",
        ],
      },
    ],
  },
  {
    id: "m3",
    slug: "inversion-basica",
    title: "Inversión Básica",
    icon: "📈",
    description: "Haz que tu dinero trabaje para ti, aunque empieces con poco.",
    gradient: "from-violet-600 to-purple-500",
    minPlan: "free",
    chapters: [
      {
        id: "m3c1",
        slug: "dinero-pierde-valor",
        title: "¿Por qué el dinero guardado pierde valor?",
        estimatedMinutes: 4,
        tags: ["inflación", "inversión", "poder adquisitivo"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "La inflación es el impuesto más cruel porque golpea a los que menos tienen.", author: "Milton Friedman" },
        summary: [
          "La inflación reduce el poder de compra de tu dinero cada año.",
          "$10,000 guardados hoy valdrán menos en 5 años en términos reales.",
          "Invertir no es opcional si quieres mantener y crecer tu patrimonio.",
        ],
      },
      {
        id: "m3c2",
        slug: "interes-compuesto",
        title: "El interés compuesto: el octavo milagro del mundo",
        estimatedMinutes: 6,
        tags: ["interés compuesto", "inversión", "tiempo"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "El interés compuesto es el octavo milagro del mundo. El que lo entiende, lo gana; el que no, lo paga.", author: "Albert Einstein" },
        summary: [
          "El interés compuesto genera intereses sobre tus intereses anteriores.",
          "El tiempo es el ingrediente más importante — empezar hoy vale más que empezar mañana.",
          "$100/mes durante 30 años al 8% = $149,036. La mitad vino de intereses.",
        ],
      },
      {
        id: "m3c3",
        slug: "tipos-de-inversion",
        title: "Tipos de inversión explicados simple",
        estimatedMinutes: 5,
        tags: ["inversión", "acciones", "bonos", "fondos"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Diversifica. La única excepción a esto es si sabes exactamente qué estás haciendo.", author: "Warren Buffett" },
        summary: [
          "Acciones = parte de una empresa. Alto riesgo, alto retorno a largo plazo.",
          "Bonos = préstamo a empresa/gobierno. Bajo riesgo, bajo retorno.",
          "Fondos índice = cesta diversificada. Ideal para empezar.",
        ],
      },
      {
        id: "m3c4",
        slug: "sp500",
        title: "El índice S&P 500 y cómo invertir en él",
        estimatedMinutes: 5,
        tags: ["S&P 500", "ETF", "índice", "inversión pasiva"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Los fondos índice de bajo costo son la inversión más sensata para la gran mayoría.", author: "Warren Buffett" },
        summary: [
          "El S&P 500 agrupa las 500 empresas más grandes de EE.UU.",
          "Ha rentado ~10% promedio anual en los últimos 100 años.",
          "Puedes invertir desde $1 con ETFs como VOO o SPY.",
        ],
      },
      {
        id: "m3c5",
        slug: "empezar-con-poco",
        title: "Cómo empezar con poco dinero",
        estimatedMinutes: 4,
        tags: ["inversión", "principiante", "poco capital"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "No esperes tener suficiente dinero para invertir. Invierte para tener suficiente dinero.", author: "Grant Cardone" },
        summary: [
          "Con $20/mes puedes comenzar en plataformas como GBM, FXORO o Robinhood.",
          "La consistencia importa más que el monto inicial.",
          "Automatiza tu aportación mensual para no depender de la disciplina.",
        ],
      },
      {
        id: "m3c6",
        slug: "proyeccion-tu-ahorro",
        title: "Con tu tasa de ahorro, ¿cuánto tendrías en 10 años?",
        estimatedMinutes: 3,
        tags: ["IA", "personalizado", "proyección"],
        hasAiSection: true,
        minPlan: "free",
        quote: { text: "Las personas que no planean su futuro financiero están planeando fallar.", author: "Tony Robbins" },
        summary: [
          "Claude calcula tu proyección real basándose en tu ahorro mensual actual.",
          "Compara escenarios: seguir igual vs. llegar al 20% de ahorro.",
          "Muestra la diferencia en dinero real que produce aumentar $100/mes.",
        ],
      },
    ],
  },
  {
    id: "m4",
    slug: "deudas",
    title: "Deudas: Cómo Eliminarlas",
    icon: "💸",
    description: "Estrategias probadas para salir de deudas y no volver a caer.",
    gradient: "from-orange-600 to-red-500",
    minPlan: "free",
    chapters: [
      {
        id: "m4c1",
        slug: "buenos-malos-deuda",
        title: "Buenos y malos tipos de deuda",
        estimatedMinutes: 4,
        tags: ["deuda", "buena deuda", "mala deuda"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "La deuda buena crea activos; la deuda mala crea gastos.", author: "Robert Kiyosaki" },
        summary: [
          "Deuda buena: genera activos o ingresos (hipoteca para rentar, préstamo de negocio).",
          "Deuda mala: financia consumo (tarjeta de ropa, crédito de vacaciones).",
          "No toda deuda es igual — el contexto y la tasa lo cambian todo.",
        ],
      },
      {
        id: "m4c2",
        slug: "bola-de-nieve-avalancha",
        title: "Método bola de nieve vs avalancha",
        estimatedMinutes: 5,
        tags: ["deuda", "bola de nieve", "avalancha", "estrategia"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Paga la deuda más pequeña primero. Las victorias rápidas crean impulso.", author: "Dave Ramsey" },
        summary: [
          "Bola de nieve: paga primero la deuda más pequeña. Más motivación.",
          "Avalancha: paga primero la deuda con mayor interés. Más ahorro matemático.",
          "Ambos funcionan — elige el que se adapta mejor a tu psicología.",
        ],
      },
      {
        id: "m4c3",
        slug: "negociacion-acreedores",
        title: "Negociación con acreedores",
        estimatedMinutes: 4,
        tags: ["negociación", "deuda", "acreedores"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Todo en la vida es negociable.", author: "Tony Robbins" },
        summary: [
          "Los bancos prefieren cobrar menos que no cobrar nada.",
          "Puedes pedir quita, reestructura o tasa reducida llamando directamente.",
          "Documenta todo por escrito antes de pagar cualquier acuerdo.",
        ],
      },
      {
        id: "m4c4",
        slug: "salir-deudas-ingreso-bajo",
        title: "Cómo salir de deudas con ingreso bajo",
        estimatedMinutes: 5,
        tags: ["deuda", "ingreso bajo", "estrategia"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "No necesitas ganar más para salir de deudas. Necesitas gastar diferente.", author: "Dave Ramsey" },
        summary: [
          "Identifica gastos recortables aunque sean pequeños — la consistencia suma.",
          "Toda entrada extra (regalo, bono, freelance) va directo a la deuda.",
          "El método del 'presupuesto de supervivencia' temporalmente acelera el pago.",
        ],
      },
      {
        id: "m4c5",
        slug: "plan-tus-deudas",
        title: "Plan para tus deudas actuales",
        estimatedMinutes: 3,
        tags: ["IA", "personalizado", "deudas"],
        hasAiSection: true,
        minPlan: "free",
        quote: { text: "La libertad financiera comienza el día que pagas tu última deuda.", author: "Dave Ramsey" },
        summary: [
          "Claude identifica tus deudas con mayor interés registradas en Buco.",
          "Genera un plan de pago mensual personalizado con tu capacidad actual.",
          "Calcula cuándo estarás libre de deudas si sigues el plan.",
        ],
      },
    ],
  },
  {
    id: "m5",
    slug: "mentalidad-millonaria",
    title: "Mentalidad Millonaria",
    icon: "🧠",
    description: "Los principios mentales de los más ricos del mundo, aplicados a tu vida.",
    gradient: "from-amber-600 to-yellow-500",
    minPlan: "free",
    chapters: [
      {
        id: "m5c1",
        slug: "cuadrante-flujo-dinero",
        title: "El Cuadrante del Flujo del Dinero (Kiyosaki)",
        estimatedMinutes: 6,
        tags: ["Kiyosaki", "ESBI", "cuadrante", "libertad financiera"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "La escuela te enseña a ser empleado. Nadie te enseña a ser dueño.", author: "Robert Kiyosaki" },
        summary: [
          "E (Empleado): intercambias tiempo por dinero. Ingresos limitados.",
          "S (Self-employed): eres el negocio. Sin ti, no hay ingreso.",
          "B (Business owner) e I (Investor): el dinero trabaja para ti.",
        ],
      },
      {
        id: "m5c2",
        slug: "activos-vs-pasivos",
        title: "Activos vs Pasivos — la diferencia que lo cambia todo",
        estimatedMinutes: 5,
        tags: ["activos", "pasivos", "Kiyosaki", "riqueza"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Los ricos compran activos. La clase media y los pobres compran pasivos creyendo que son activos.", author: "Robert Kiyosaki" },
        summary: [
          "Activo: pone dinero en tu bolsillo (renta, dividendos, royalties).",
          "Pasivo: saca dinero de tu bolsillo (auto, ropa cara, deudas de consumo).",
          "La clave: construir una columna de activos antes de aumentar el estilo de vida.",
        ],
      },
      {
        id: "m5c3",
        slug: "7-pasos-libertad-financiera",
        title: "Los 7 pasos hacia la libertad financiera",
        estimatedMinutes: 6,
        tags: ["libertad financiera", "pasos", "plan"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "La libertad financiera no es una cantidad de dinero. Es un estado mental.", author: "Tony Robbins" },
        summary: [
          "Paso 1: Fondo de emergencia (3-6 meses de gastos).",
          "Pasos 2-4: Eliminar deudas y automatizar ahorro e inversión.",
          "Pasos 5-7: Construir activos hasta que los ingresos pasivos cubran tus gastos.",
        ],
      },
      {
        id: "m5c4",
        slug: "mentalidad-escasez-abundancia",
        title: "La mentalidad de escasez vs abundancia",
        estimatedMinutes: 4,
        tags: ["T. Harv Eker", "mentalidad", "escasez", "abundancia"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Los pensamientos llevan a sentimientos, que llevan a acciones, que llevan a resultados. Todo empieza en tu cabeza.", author: "T. Harv Eker" },
        summary: [
          "Mentalidad de escasez: el dinero es limitado, hay que guardarlo con miedo.",
          "Mentalidad de abundancia: hay suficiente para todos; el dinero viene y va.",
          "Tu 'termostato financiero' interno determina cuánto permites que entre y se quede.",
        ],
      },
      {
        id: "m5c5",
        slug: "6-cuentas-millonarias",
        title: "Las 6 cuentas millonarias de T. Harv Eker",
        estimatedMinutes: 5,
        tags: ["T. Harv Eker", "cuentas", "sistema financiero"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Si no manejas bien $1, el universo no te confiará $1,000,000.", author: "T. Harv Eker" },
        summary: [
          "55% Necesidades · 10% Ahorro largo plazo · 10% Educación.",
          "10% Diversión · 10% Inversión · 5% Donación.",
          "El sistema funciona aunque sea en pequeño — los porcentajes crean el hábito.",
        ],
      },
      {
        id: "m5c6",
        slug: "piensa-hagase-rico",
        title: "Piensa y Hágase Rico — los 13 principios",
        estimatedMinutes: 8,
        tags: ["Napoleon Hill", "13 principios", "éxito", "mentalidad"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Todo lo que la mente puede concebir y creer, puede lograrse.", author: "Napoleon Hill" },
        summary: [
          "Deseo ardiente + Fe + Autosugestión: los 3 primeros principios más poderosos.",
          "El conocimiento especializado y la imaginación crean planes concretos.",
          "La perseverencia y la mente maestra son los aceleradores del éxito.",
        ],
      },
      {
        id: "m5c7",
        slug: "leyes-universales-dinero",
        title: "Las leyes universales del dinero (Bob Proctor)",
        estimatedMinutes: 5,
        tags: ["Bob Proctor", "leyes universales", "vibración", "dinero"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "El dinero es un resultado. La riqueza es un resultado. La salud es un resultado. La enfermedad es un resultado. Vivimos en un mundo de causa y efecto.", author: "Bob Proctor" },
        summary: [
          "La ley de vibración: tu estado mental atrae circunstancias financieras similares.",
          "La ley de causa y efecto: cada resultado financiero tiene una causa mental anterior.",
          "Cambiar tus creencias sobre el dinero es el trabajo más lucrativo que puedes hacer.",
        ],
      },
      {
        id: "m5c8",
        slug: "citas-mentores",
        title: "Citas y principios de los mejores mentores financieros",
        estimatedMinutes: 6,
        tags: ["Warren Buffett", "Ray Dalio", "Tony Robbins", "Grant Cardone", "mentores"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Regla N°1: Nunca pierdas dinero. Regla N°2: Nunca olvides la regla N°1.", author: "Warren Buffett" },
        summary: [
          "Warren Buffett: invierte en lo que entiendes, sé paciente y huye de las deudas.",
          "Ray Dalio: diversifica, entiende los ciclos económicos y sé humilde.",
          "Grant Cardone: 10X todo, nunca ahorres dinero que no estés invirtiendo.",
        ],
      },
    ],
  },
  {
    id: "m6",
    slug: "habitos-financieros",
    title: "Hábitos Financieros",
    icon: "🔄",
    description: "Construye los sistemas que hacen que el éxito financiero sea automático.",
    gradient: "from-cyan-600 to-blue-500",
    minPlan: "free",
    chapters: [
      {
        id: "m6c1",
        slug: "por-que-fallamos",
        title: "Por qué fallamos con el dinero (psicología)",
        estimatedMinutes: 5,
        tags: ["psicología", "comportamiento", "sesgos"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "La mayor barrera para el éxito financiero no es el dinero. Es el comportamiento.", author: "Dave Ramsey" },
        summary: [
          "El sesgo del presente nos hace preferir placer inmediato sobre bienestar futuro.",
          "La fatiga de decisión agota la fuerza de voluntad con cada elección del día.",
          "Automatizar decisiones financieras elimina la necesidad de fuerza de voluntad.",
        ],
      },
      {
        id: "m6c2",
        slug: "5-habitos-libres",
        title: "Los 5 hábitos de las personas financieramente libres",
        estimatedMinutes: 5,
        tags: ["hábitos", "libertad financiera", "rutinas"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Primero forjamos nuestros hábitos, luego nuestros hábitos nos forjan a nosotros.", author: "John Dryden" },
        summary: [
          "Revisión financiera semanal de 10 minutos: saber exactamente qué entra y qué sale.",
          "Regla de 24h para compras impulsivas: duerme antes de comprar.",
          "Meta de ahorro automática el día de cobro, sin negociación interna.",
        ],
      },
      {
        id: "m6c3",
        slug: "automatizar-finanzas",
        title: "Automatizar tus finanzas",
        estimatedMinutes: 4,
        tags: ["automatización", "ahorro automático", "inversión automática"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Configura tus finanzas para que funcionen sin que tú tengas que hacer nada.", author: "Ramit Sethi" },
        summary: [
          "El día de cobro: ahorro → inversión → gastos fijos → lo demás es libre.",
          "Automatiza con transferencias programadas antes de que veas el dinero.",
          "Buco te avisa cuando algo en tu plan cambia inesperadamente.",
        ],
      },
      {
        id: "m6c4",
        slug: "revision-financiera",
        title: "La revisión financiera semanal y mensual",
        estimatedMinutes: 4,
        tags: ["revisión", "hábito", "control financiero"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Lo que no se mide no se puede mejorar.", author: "Peter Drucker" },
        summary: [
          "Revisión semanal (10 min): ¿qué gasté? ¿estoy en presupuesto?",
          "Revisión mensual (30 min): análisis completo, ajustes al plan, celebrar logros.",
          "Buco genera tu reporte mensual automáticamente en /reports.",
        ],
      },
      {
        id: "m6c5",
        slug: "buco-habitos",
        title: "Cómo Buco te ayuda a mantener los hábitos",
        estimatedMinutes: 3,
        tags: ["buco", "hábitos", "tutorial"],
        hasAiSection: false,
        minPlan: "free",
        quote: { text: "Un sistema bueno supera a la mejor intención.", author: "James Clear" },
        summary: [
          "Usa los recordatorios de Buco para la revisión semanal del domingo.",
          "El dashboard muestra tu racha de días sin exceder presupuesto.",
          "Las metas de hábito registran tu consistencia mes a mes.",
        ],
      },
      {
        id: "m6c6",
        slug: "tus-habitos-analizados",
        title: "Tus hábitos actuales analizados",
        estimatedMinutes: 3,
        tags: ["IA", "personalizado", "hábitos"],
        hasAiSection: true,
        minPlan: "free",
        quote: { text: "Conocerse a uno mismo es el inicio de toda sabiduría financiera.", author: "Aristóteles (adaptado)" },
        summary: [
          "Claude detecta patrones de gasto recurrentes en tu historial.",
          "Identifica tus días y horarios de mayor gasto impulsivo.",
          "Sugiere un cambio de hábito específico basado en tus datos reales.",
        ],
      },
    ],
  },
];

export function getModule(slug: string): Module | undefined {
  return MODULES.find((m) => m.slug === slug);
}

export function getChapter(moduleSlug: string, chapterSlug: string): { module: Module; chapter: Chapter } | undefined {
  const mod = getModule(moduleSlug);
  if (!mod) return undefined;
  const chapter = mod.chapters.find((c) => c.slug === chapterSlug);
  if (!chapter) return undefined;
  return { module: mod, chapter };
}

export const TOTAL_CHAPTERS = MODULES.reduce((acc, m) => acc + m.chapters.length, 0);
